#include "Misc/AutomationTest.h"
#include "EmberWeaponDefinition.h"

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FEmberWeaponStableIdentityTest,
    "ProjectEmber.Core.WeaponStableIdentity",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FEmberWeaponStableIdentityTest::RunTest(const FString& Parameters)
{
    UEmberWeaponDefinition* Definition = NewObject<UEmberWeaponDefinition>();
    Definition->Identifier = TEXT("Weapon.StandardRifle");
    const FPrimaryAssetId Id = Definition->GetPrimaryAssetId();
    TestEqual(TEXT("Primary asset type is stable"), Id.PrimaryAssetType.ToString(), FString(TEXT("EmberWeapon")));
    TestEqual(TEXT("Primary asset name uses semantic identifier"), Id.PrimaryAssetName, FName(TEXT("Weapon.StandardRifle")));

    const UEmberWeaponDefinition* MissionRifle = LoadObject<UEmberWeaponDefinition>(
        nullptr, TEXT("/Game/Ember/Weapons/DA_Weapon_AshlineA4.DA_Weapon_AshlineA4"));
    TestNotNull(TEXT("Mission rifle definition is generated by the Editor commandlet"), MissionRifle);
    if (MissionRifle)
    {
        TestTrue(TEXT("Mission rifle has a licensed fire animation reference"),
            !MissionRifle->FireAnimation.IsNull());
        TestTrue(TEXT("Mission rifle has a licensed reload animation reference"),
            !MissionRifle->ReloadAnimation.IsNull());
    }
    return true;
}
