#pragma once

#include "CoreMinimal.h"

EMBERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogEmber, Log, All);
EMBERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogEmberCombat, Log, All);
EMBERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogEmberAI, Log, All);
EMBERCORE_API DECLARE_LOG_CATEGORY_EXTERN(LogEmberMission, Log, All);

